#! /bin/sh

# Adding the w flag (wait) slows down the script
# as it must wait for the proccess to end, but helps
# in making sure it behaves as expected.
killall -q -w polybar
killall -q -w picom

pgrep -x sxhkd > /dev/null || sxhkd &

MONITORS=$(xrandr | grep " connected " | awk '{ print$1 }')
MONITORS=(${MONITORS//$'\n'/ })

DESKTOPS=("I" "II" "III" "IV" "V" "VI" "VII" "VIII")
DESKTOPS_PER_MONITOR=$(( 8 / ${#MONITORS[@]} ))
CURRENT_DESKTOP=0

for MONITOR in ${MONITORS[@]}
do
  bspc monitor $MONITOR -d ${DESKTOPS[@]:$CURRENT_DESKTOP:(($CURRENT_DESKTOP+$DESKTOPS_PER_MONITOR))}
  ((CURRENT_DESKTOP=$CURRENT_DESKTOP+$DESKTOPS_PER_MONITOR))
done

bspc monitor -a 9
bspc config border_width         	1
bspc config normal_border_color		'#323232'
bspc config active_border_color		'#464646'
bspc config focused_border_color	'#464646'

$HOME/.config/bspwm/gapped-mode.sh setup
$HOME/.config/bspwm/padded-mode.sh setup
$HOME/.config/bspwm/toggle-window-start-state.sh setup
$HOME/.config/bspwm/floating-window-default-sizes.sh

set-wallpaper

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color '#f2e0ce'

# Opens polybar on each monitor found by xrandr.
if type "xrandr"; then
	for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		MONITOR=$m polybar --reload example &
	done
else
	polybar --reload example &
fi

# Start picom, the experimental-backends flag is 
# required for some features.
picom --experimental-backends

